version: '3.8'
services:
  web_server:
    image: nginx:1.19
    ports:
      - "9099:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - task_manager
  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - ./.docker/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./:/var/www/html
    ports:
      - "9006:9000"
    networks:
      - task_manager
    environment:
      PHP_IDE_CONFIG: serverName=taskManager
      XDEBUG_CONFIG: "remote_host=php remote_enable=1"
  database:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd123
      MYSQL_DATABASE: tasks
      MYSQL_USER: db_user
      MYSQL_PASSWORD: pwd123
    networks:
      - task_manager
    restart: on-failure
    volumes:
      - database-data:/var/lib/mysql
    ports:
      - "33069:3306"
  rabbitmq:
    image: rabbitmq:3.8-management
    networks:
      - task_manager
    ports:
      - 5673:5672
      - 15673:15672
  cache:
    image: memcached:1.6-alpine
    networks:
      - task_manager
    ports:
      - "11213:11211"
    restart: on-failure
  minio:
    image: minio/minio
    ports:
      - "9001:9000"
      - "9002:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: userpwd123
    depends_on:
      - php
    networks:
      - task_manager
    command: server --console-address ":9001" /data;
  mc:
    image: minio/mc:latest
    networks:
      - task_manager
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host rm local;
      /usr/bin/mc config host add --quiet --api s3v4 local http://minio:9000 user userpwd123;
      /usr/bin/mc mb --quiet local/avatar/;
      /usr/bin/mc anonymous set public local/avatar;
      "
volumes:
  minio_storage: {}
  database-data:
  elasticsearch:

networks:
  task_manager:
    driver: bridge
