version: '3.8'
services:
  web_server:
    image: nginx:1.19
    ports:
      - "9099:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - ./.docker/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./:/var/www/html
    ports:
      - "9006:9000"
    networks:
      - backend
    environment:
      PHP_IDE_CONFIG: serverName=app
      XDEBUG_CONFIG: "remote_host=php remote_enable=1"
  database:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd123
      MYSQL_DATABASE: tasks
      MYSQL_USER: db_user
      MYSQL_PASSWORD: pwd123
    networks:
      - backend
    restart: on-failure
    volumes:
      - database-data:/var/lib/mysql
    ports:
      - "33069:3306"
  rabbitmq:
    image: rabbitmq:3.8-management
    networks:
      - backend
    ports:
      - 5673:5672
      - 15673:15672
  cache:
    image: memcached:1.6-alpine
    networks:
      - backend
    ports:
      - "11213:11211"
    restart: on-failure
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: masoud
      MINIO_ROOT_PASSWORD: Strong#Pass#2022
    depends_on:
      - php
    networks:
      - backend
    command: server --console-address ":9001" /data

volumes:
  minio_storage: {}
  database-data:
  elasticsearch:

networks:
  backend:
    driver: bridge
    external:
      name: backend
